class DataItems {
    constructor() {
        this.data = new Map()

        this.data.set("1", {
            id: 1,
            nom: "item1",
            cout: 10,
            nbBois: 1,
            nbOr: 2,
            nbArgile: 0,
            nbNourriture: 0,
            nbPierre: 0,
            nbMetal1: 0,
            nbMetal2: 0,
            nbMetal3: 0,
            nbMetal4: 0,
            nbMetal5: 0,
            nbMetal6: 0,
            nbBois1: 0,
            nbBois2: 0,
            nbBois3: 0,
            nbBois4: 0,
            nbBois5: 0,
            idEffets: [],
        })
        this.data.set("2", {
            id: 2,
            nom: "item2",
            cout: 10,
            nbBois: 1,
            nbOr: 2,
            nbArgile: 0,
            nbNourriture: 0,
            nbPierre: 0,
            nbMetal1: 0,
            nbMetal2: 0,
            nbMetal3: 0,
            nbMetal4: 0,
            nbMetal5: 0,
            nbMetal6: 0,
            nbBois1: 0,
            nbBois2: 0,
            nbBois3: 0,
            nbBois4: 0,
            nbBois5: 0,
            idEffets: [],
        })
        this.data.set("3", {
            id: 3,
            nom: "item3",
            cout: 10,
            nbBois: 1,
            nbOr: 2,
            nbArgile: 0,
            nbNourriture: 0,
            nbPierre: 0,
            nbMetal1: 0,
            nbMetal2: 0,
            nbMetal3: 0,
            nbMetal4: 0,
            nbMetal5: 0,
            nbMetal6: 0,
            nbBois1: 0,
            nbBois2: 0,
            nbBois3: 0,
            nbBois4: 0,
            nbBois5: 0,
            idEffets: [],
        })
        this.data.set("4", {
            id: 4,
            nom: "item4",
            cout: 10,
            nbBois: 1,
            nbOr: 2,
            nbArgile: 0,
            nbNourriture: 0,
            nbPierre: 0,
            nbMetal1: 0,
            nbMetal2: 0,
            nbMetal3: 0,
            nbMetal4: 0,
            nbMetal5: 0,
            nbMetal6: 0,
            nbBois1: 0,
            nbBois2: 0,
            nbBois3: 0,
            nbBois4: 0,
            nbBois5: 0,
            idEffets: [],
        })
        this.data.set("5", {
            id: 5,
            nom: "item5",
            cout: 10,
            nbBois: 1,
            nbOr: 2,
            nbArgile: 0,
            nbNourriture: 0,
            nbPierre: 0,
            nbMetal1: 0,
            nbMetal2: 0,
            nbMetal3: 0,
            nbMetal4: 0,
            nbMetal5: 0,
            nbMetal6: 0,
            nbBois1: 0,
            nbBois2: 0,
            nbBois3: 0,
            nbBois4: 0,
            nbBois5: 0,
            idEffets: [],
        })
    }
    getData() {
        return this.data
    }
}
export { DataItems }